"""HTML template helper for report-domain HTML output."""

from __future__ import annotations

from pathlib import Path
from typing import Any


def render_report_html_document(
    project_name: str,
    project_path: Path,
    generated_at_iso: str,
    stats_payload: dict[str, int],
    python_script_count: int,
    config_snapshot: dict[str, Any] | None,
) -> str:
    perf = (config_snapshot or {}).get("performance", {})
    git = (config_snapshot or {}).get("git", {})

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{project_name} - UnrealMate Report</title>
    <style>
        body {{ font-family: 'Segoe UI', sans-serif; background: #1a1a2e; color: #eee; padding: 40px; }}
        h1 {{ color: #00d4ff; border-bottom: 2px solid #00d4ff; padding-bottom: 10px; }}
        h2 {{ color: #a855f7; margin-top: 30px; }}
        table {{ border-collapse: collapse; width: 100%; margin: 15px 0; }}
        th, td {{ border: 1px solid #333; padding: 10px; text-align: left; }}
        th {{ background: #16213e; color: #00d4ff; }}
        td {{ background: #0f3460; }}
        .footer {{ margin-top: 40px; color: #666; font-size: 12px; }}
    </style>
</head>
<body>
    <h1>{project_name} - Project Report</h1>
    <p>Generated: {generated_at_iso}</p>

    <h2>Project Overview</h2>
    <table>
        <tr><th>Metric</th><th>Value</th></tr>
        <tr><td>Project Name</td><td>{project_name}</td></tr>
        <tr><td>Project Path</td><td>{project_path}</td></tr>
        <tr><td>.uproject files</td><td>{stats_payload.get("uproject_files", 0)}</td></tr>
        <tr><td>C++ source files</td><td>{stats_payload.get("cpp_source_files", 0)}</td></tr>
        <tr><td>Blueprints / Assets</td><td>{stats_payload.get("blueprint_assets", 0)}</td></tr>
        <tr><td>Scene maps (.umap)</td><td>{stats_payload.get("scene_maps", 0)}</td></tr>
        <tr><td>Python scripts</td><td>{python_script_count}</td></tr>
    </table>

    <h2>Configuration</h2>
    <table>
        <tr><th>Setting</th><th>Value</th></tr>
        <tr><td>Cache enabled</td><td>{perf.get("cache_enabled", "N/A")}</td></tr>
        <tr><td>Parallel processing</td><td>{perf.get("parallel_processing", "N/A")}</td></tr>
        <tr><td>Max workers</td><td>{perf.get("max_workers", "N/A")}</td></tr>
        <tr><td>Git LFS auto</td><td>{git.get("auto_lfs", "N/A")}</td></tr>
    </table>

    <div class="footer">Generated by UnrealMate CLI | © 2026 G & E ZYNTH</div>
</body>
</html>"""

